// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// CasbinRule is the golang structure for table casbin_rule.
type CasbinRule internal.CasbinRule

// Fill with you ideas below.