// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// GenTableColumn is the golang structure for table gen_table_column.
type GenTableColumn internal.GenTableColumn

// Fill with you ideas below.