// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// GenTable is the golang structure for table gen_table.
type GenTable internal.GenTable

// Fill with you ideas below.

type GenTableExtend struct {
	GenTable
	TreeCode       string           `json:"treeCode"`       // 树编码字段
	TreeParentCode string           `json:"treeParentCode"` // 树父编码字段
	TreeName       string           `json:"treeName"`       // 树名称字段
	Columns        []GenTableColumn `json:"columns"`        // 表列信息
	PkColumn       GenTableColumn   `json:"pkColumn"`       // 表列信息
}
