// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysConfig is the golang structure for table sys_config.
type SysConfig internal.SysConfig

// Fill with you ideas below.