// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysOperLog is the golang structure for table sys_oper_log.
type SysOperLog internal.SysOperLog

// Fill with you ideas below.