// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysLogininfor is the golang structure for table sys_logininfor.
type SysLogininfor internal.SysLogininfor

// Fill with you ideas below.