// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysUserRole is the golang structure for table sys_user_role.
type SysUserRole internal.SysUserRole

// Fill with you ideas below.