// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysDept is the golang structure for table sys_dept.
type SysDept internal.SysDept

// Fill with you ideas below.

type SysDeptExtend struct {
	SysDept
	ParentName string          `json:"parentName"` // 父菜单名称
	Children   []*SysDeptExtend `json:"children,omitempty"`
}

type DeptExtend struct {
	Id       int64        `json:"id"`
	Label    string       `json:"label"`
	Children []DeptExtend `json:"children,omitempty"`
}