// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysUserPost is the golang structure for table sys_user_post.
type SysUserPost internal.SysUserPost

// Fill with you ideas below.