// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysNotice is the golang structure for table sys_notice.
type SysNotice internal.SysNotice

// Fill with you ideas below.