// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysDictType is the golang structure for table sys_dict_type.
type SysDictType internal.SysDictType

// Fill with you ideas below.