// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysJobLog is the golang structure for table sys_job_log.
type SysJobLog internal.SysJobLog

// Fill with you ideas below.