// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysJob is the golang structure for table sys_job.
type SysJob internal.SysJob

// Fill with you ideas below.