// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
	"github.com/gogf/gf/container/garray"
	"github.com/gogf/gf/frame/g"
)

// SysUser is the golang structure for table sys_user.
type SysUser internal.SysUser

type SysUserInfo struct {
	User        *SysUserExtend   `json:"user,omitempty"`
	Permissions *garray.StrArray `json:"permissions,omitempty"`
	Roles       g.Array          `json:"roles,omitempty"`
	RoleIds     []int64          `json:"roleIds,omitempty"`
	Posts       []SysPostFlag    `json:"posts,omitempty"`
	PostIds     []int64          `json:"postIds,omitempty"`
	PostGroup   string           `json:"postGroup,omitempty"`
	RoleGroup   string           `json:"roleGroup,omitempty"`
}

type SysUserExtend struct {
	SysUser
	Dept  *SysDeptExtend `json:"dept"`
	Roles []SysRoleFlag  `json:"roles"`
}

type UserListItem struct {
	UserId      int64  `json:"user_id"`
	DeptId      int64  `json:"dept_id"`
	LoginName   string `json:"login_name"`
	UserName    string `json:"user_name"`
	Email       string `json:"email"`
	Avatar      string `json:"avatar"`
	Phonenumber string `json:"phonenumber"`
	Password    string `json:"password"`
	Sex         string `json:"sex"`
	Salt        string `json:"salt"`
	Status      string `json:"status"`
	DelFlag     string `json:"del_flag"`
	LoginIp     string `json:"login_ip"`
	LoginDate   string `json:"login_date"`
	CreateBy    string `json:"create_by"`
	CreateTime  string `json:"create_time"`
	Remark      string `json:"remark"`
	DeptName    string `json:"dept_name"`
	Leader      string `json:"leader"`
}
