// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysRoleMenu is the golang structure for table sys_role_menu.
type SysRoleMenu internal.SysRoleMenu

// Fill with you ideas below.