// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysRoleDept is the golang structure for table sys_role_dept.
type SysRoleDept internal.SysRoleDept

// Fill with you ideas below.