// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gea/app/model/internal"
)

// SysDictData is the golang structure for table sys_dict_data.
type SysDictData internal.SysDictData

// Fill with you ideas below.