// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// CasbinRule is the golang structure for table casbin_rule.
type CasbinRule struct {
    Ptype string `orm:"ptype" json:"ptype"` //   
    V0    string `orm:"v0"    json:"v_0"`   //   
    V1    string `orm:"v1"    json:"v_1"`   //   
    V2    string `orm:"v2"    json:"v_2"`   //   
    V3    string `orm:"v3"    json:"v_3"`   //   
    V4    string `orm:"v4"    json:"v_4"`   //   
    V5    string `orm:"v5"    json:"v_5"`   //   
}