// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysRole is the golang structure for table sys_role.
type SysRole struct {
    RoleId     int64       `orm:"role_id,primary" json:"role_id"`     // 角色ID                                                                                 
    RoleName   string      `orm:"role_name"       json:"role_name"`   // 角色名称                                                                               
    RoleKey    string      `orm:"role_key"        json:"role_key"`    // 角色权限字符串                                                                         
    RoleSort   int         `orm:"role_sort"       json:"role_sort"`   // 显示顺序                                                                               
    DataScope  string      `orm:"data_scope"      json:"data_scope"`  // 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）  
    Status     string      `orm:"status"          json:"status"`      // 角色状态（0正常 1停用）                                                                
    DelFlag    string      `orm:"del_flag"        json:"del_flag"`    // 删除标志（0代表存在 2代表删除）                                                        
    CreateBy   string      `orm:"create_by"       json:"create_by"`   // 创建者                                                                                 
    CreateTime *gtime.Time `orm:"create_time"     json:"create_time"` // 创建时间                                                                               
    UpdateBy   string      `orm:"update_by"       json:"update_by"`   // 更新者                                                                                 
    UpdateTime *gtime.Time `orm:"update_time"     json:"update_time"` // 更新时间                                                                               
    Remark     string      `orm:"remark"          json:"remark"`      // 备注                                                                                   
}