// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysNotice is the golang structure for table sys_notice.
type SysNotice struct {
    NoticeId      int         `orm:"notice_id,primary" json:"notice_id"`      // 公告ID                   
    NoticeTitle   string      `orm:"notice_title"      json:"notice_title"`   // 公告标题                 
    NoticeType    string      `orm:"notice_type"       json:"notice_type"`    // 公告类型（1通知 2公告）  
    NoticeContent string      `orm:"notice_content"    json:"notice_content"` // 公告内容                 
    Status        string      `orm:"status"            json:"status"`         // 公告状态（0正常 1关闭）  
    CreateBy      string      `orm:"create_by"         json:"create_by"`      // 创建者                   
    CreateTime    *gtime.Time `orm:"create_time"       json:"create_time"`    // 创建时间                 
    UpdateBy      string      `orm:"update_by"         json:"update_by"`      // 更新者                   
    UpdateTime    *gtime.Time `orm:"update_time"       json:"update_time"`    // 更新时间                 
    Remark        string      `orm:"remark"            json:"remark"`         // 备注                     
}