// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysDictData is the golang structure for table sys_dict_data.
type SysDictData struct {
    DictCode   int64       `orm:"dict_code,primary" json:"dict_code"`   // 字典编码             
    DictSort   int         `orm:"dict_sort"         json:"dict_sort"`   // 字典排序             
    DictLabel  string      `orm:"dict_label"        json:"dict_label"`  // 字典标签             
    DictValue  string      `orm:"dict_value"        json:"dict_value"`  // 字典键值             
    DictType   string      `orm:"dict_type"         json:"dict_type"`   // 字典类型             
    Status     string      `orm:"status"            json:"status"`      // 状态（0正常 1停用）  
    CreateBy   string      `orm:"create_by"         json:"create_by"`   // 创建者               
    CreateTime *gtime.Time `orm:"create_time"       json:"create_time"` // 创建时间             
    UpdateBy   string      `orm:"update_by"         json:"update_by"`   // 更新者               
    UpdateTime *gtime.Time `orm:"update_time"       json:"update_time"` // 更新时间             
    Remark     string      `orm:"remark"            json:"remark"`      // 备注                 
}