// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysUserPost is the golang structure for table sys_user_post.
type SysUserPost struct {
    UserId int64 `orm:"user_id,primary" json:"user_id"` // 用户ID  
    PostId int64 `orm:"post_id,primary" json:"post_id"` // 岗位ID  
}