// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysRoleDept is the golang structure for table sys_role_dept.
type SysRoleDept struct {
    RoleId int64 `orm:"role_id,primary" json:"role_id"` // 角色ID  
    DeptId int64 `orm:"dept_id,primary" json:"dept_id"` // 部门ID  
}