// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysJobLog is the golang structure for table sys_job_log.
type SysJobLog struct {
    JobLogId      int64       `orm:"job_log_id,primary" json:"job_log_id"`     // 任务日志ID               
    JobName       string      `orm:"job_name"           json:"job_name"`       // 任务名称                 
    JobGroup      string      `orm:"job_group"          json:"job_group"`      // 任务组名                 
    InvokeTarget  string      `orm:"invoke_target"      json:"invoke_target"`  // 调用目标字符串           
    JobMessage    string      `orm:"job_message"        json:"job_message"`    // 日志信息                 
    Status        string      `orm:"status"             json:"status"`         // 执行状态（0正常 1失败）  
    ExceptionInfo string      `orm:"exception_info"     json:"exception_info"` // 异常信息                 
    CreateTime    *gtime.Time `orm:"create_time"        json:"create_time"`    // 创建时间                 
}