// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// SysConfig is the golang structure for table sys_config.
type SysConfig struct {
    ConfigId    int         `orm:"config_id,primary" json:"config_id"`    // 参数主键             
    ConfigName  string      `orm:"config_name"       json:"config_name"`  // 参数名称             
    ConfigKey   string      `orm:"config_key"        json:"config_key"`   // 参数键名             
    ConfigValue string      `orm:"config_value"      json:"config_value"` // 参数键值             
    ConfigType  string      `orm:"config_type"       json:"config_type"`  // 系统内置（Y是 N否）  
    CreateBy    string      `orm:"create_by"         json:"create_by"`    // 创建者               
    CreateTime  *gtime.Time `orm:"create_time"       json:"create_time"`  // 创建时间             
    UpdateBy    string      `orm:"update_by"         json:"update_by"`    // 更新者               
    UpdateTime  *gtime.Time `orm:"update_time"       json:"update_time"`  // 更新时间             
    Remark      string      `orm:"remark"            json:"remark"`       // 备注                 
}