// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysUserRole is the golang structure for table sys_user_role.
type SysUserRole struct {
    UserId int64 `orm:"user_id,primary" json:"user_id"` // 用户ID  
    RoleId int64 `orm:"role_id,primary" json:"role_id"` // 角色ID  
}