// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SysRoleMenu is the golang structure for table sys_role_menu.
type SysRoleMenu struct {
    RoleId int64 `orm:"role_id,primary" json:"role_id"` // 角色ID  
    MenuId int64 `orm:"menu_id,primary" json:"menu_id"` // 菜单ID  
}