# HTTP Server
[status]
    admin = true
    api = false

[admin]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gea"
	LogPath     = "log/gea/server"
	DumpRouterMap = false
    prefix = "/api"
[api]
	Address     = ":8090"
	ServerRoot  = "public"
	ServerAgent = "gea"
	LogPath     = "log/gea/api"
	DumpRouterMap = false

#jwt配置
[jwt]
    #过期时间
    timeout = 864000
    #token分割符
    refresh = 1800
    #安全密钥
    encryptKey = "geazxc0123lk0912"
    cache = "default"   # default/redis
[gtoken]
    CacheMode = 1
    Timeout =  0
    MaxRefresh = 0
    EncryptKey = "geazxc0123lk0912"
    AuthFailMsg = "登录超时，请重新登录"
    MultiLogin = true

# Logger.
[logger]
    AppName     = "gea-local"
    Path        = "log/gea"
    Level       = "all"
    Stdout      = true
    RotateSize  = "2M"
    RotateBackupLimit    = 10
    RotateBackupExpire   = "7d"
    RotateBackupCompress = 9
# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]

# Database.
[database]
    [database.default]
        link  = "mysql:root:@tcp(127.0.0.1:3306)/gea"
        debug = true
    [database.logger]
        Path   = "log/gea/sql"
        Level  = "all"
        Stdout = true
[casbin]
    driverName = "mysql"
    dataSourceName = "root:@tcp(127.0.0.1:3306)/gea"

# Gen
[gen]
    author        = "1307"
    moduleName    = "admin"
    packageName   = "gea"
    autoRemovePre = true
    tablePrefix   = "t_,sys_"

[compiler]
    name     = "gea"
    version  = "1.0.0"
    arch     = "386,amd64"
    system   = "windows,darwin"
    output   = ""
    path     = "./bin"
    extra    = "-ldflags \"-s -w\""
    # 自定义编译时内置变量
    [compiler.VarMap]
        author = "1307"
        email  = "1307@qq.com"
[logstash]
    Enable = false
    Ip = ""
    Port = ""
    AppName = "gea"
    Type = "application"
    TimeOut = 5

[apollo]
    Enable = false
    AppId = ""
    Cluster = "default"
    NamespaceName = "application"
    Ip = ""
    NextTryConnTime = 0
# Redis数据库配置
[redis]
    default  = "127.0.0.1:6379,3"
    cache = "127.0.0.1:6379,4"