[profile]
    active = "local"
# Database.
[database]
    [database.default]
        link  = "mysql:root:@tcp(127.0.0.1:3306)/gea"
        debug = true
    [database.logger]
        Path   = "log/gea/sql"
        Level  = "all"
        Stdout = true
[compiler]
    name     = "gea"
    version  = "dev-1.0.0"
    arch     = "amd64"
    system   = "linux"
    output   = ""
    path     = "./bin"
    extra    = "-ldflags \"-s -w\""
    # 自定义编译时内置变量
    [compiler.VarMap]
        author = "1307"
        email  = "1307@qq.com"