// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gea/app/dao/internal"
)

// genTableColumnDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type genTableColumnDao struct {
	*internal.GenTableColumnDao
}

var (
	// GenTableColumn is globally public accessible object for table gen_table_column operations.
	GenTableColumn = &genTableColumnDao{
		internal.GenTableColumn,
	}
)

// Fill with you ideas below.