// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gea/app/dao/internal"
)

// sysDeptDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysDeptDao struct {
	*internal.SysDeptDao
}

var (
	// SysDept is globally public accessible object for table sys_dept operations.
	SysDept = &sysDeptDao{
		internal.SysDept,
	}
)

// Fill with you ideas below.