// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gea/app/dao/internal"
)

// sysUserDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysUserDao struct {
	*internal.SysUserDao
}

var (
	// SysUser is globally public accessible object for table sys_user operations.
	SysUser = &sysUserDao{
		internal.SysUser,
	}
)

// Fill with you ideas below.
