// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gea/app/dao/internal"
)

// sysUserRoleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysUserRoleDao struct {
	*internal.SysUserRoleDao
}

var (
	// SysUserRole is globally public accessible object for table sys_user_role operations.
	SysUserRole = &sysUserRoleDao{
		internal.SysUserRole,
	}
)

// Fill with you ideas below.