// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gea/app/dao/internal"
)

// sysOperLogDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysOperLogDao struct {
	*internal.SysOperLogDao
}

var (
	// SysOperLog is globally public accessible object for table sys_oper_log operations.
	SysOperLog = &sysOperLogDao{
		internal.SysOperLog,
	}
)

// Fill with you ideas below.