// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gea/app/dao/internal"
)

// sysPostDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysPostDao struct {
	*internal.SysPostDao
}

var (
	// SysPost is globally public accessible object for table sys_post operations.
	SysPost = &sysPostDao{
		internal.SysPost,
	}
)

// Fill with you ideas below.