// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gea/app/dao/internal"
)

// sysJobLogDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysJobLogDao struct {
	*internal.SysJobLogDao
}

var (
	// SysJobLog is globally public accessible object for table sys_job_log operations.
	SysJobLog = &sysJobLogDao{
		internal.SysJobLog,
	}
)

// Fill with you ideas below.